let allAlcohols = [
    ["1554 Enlightened Black Ale   ", " 5.6% ABV ", " 12oz serving"]
    ["1910 Rye Whisky ", " 40% ABV ", " 1.5oz serving"]
    ["Abbots Lager ", " 4.5% ABV ", " 12oz serving"]
    ["Absinthe ", " 50% ABV ", " 1.5oz serving"]
    ["Absolut Vodka ", " 40% ABV ", " 1.5oz serving"]
    ["Addlestones Cider ", " 5% ABV ", " 12oz serving"]
    ["Aguila ", " 3.9% ABV ", " 12oz serving"]
    ["Alaskan Amber   ", " 5.3% ABV ", " 12oz serving"]
    ["Alaskan IPA   ", " 6.2% ABV ", " 12oz serving"]
    ["Alaskan Pale   ", " 5.2% ABV ", " 12oz serving"]
    ["Alcohol Inspired Refresher (AIR) ", " 4% ABV ", " 12oz serving"]
    ["AleSmith Anvil ESB   ", " 5.5% ABV ", " 12oz serving"]
    ["AleSmith IPA    ", " 7.25% ABV ", " 12oz serving"]
    ["AleSmith Old Numbskull   ", " 11% ABV ", " 12oz serving"]
    ["AleSmith Speedway Stout   ", " 12% ABV ", " 12oz serving"]
    ["AleSmith X   ", " 5.25% ABV ", " 12oz serving"]
    ["Alexander Keiths Brown Ale ", " 5.4% ABV ", " 12oz serving"]
    ["Alexander Keiths Lager ", " 5.4% ABV ", " 12oz serving"]
    ["Alexander Keiths Pale Ale   ", " 5.4% ABV ", " 12oz serving"]
    ["Amstel Light   ", " 3.5% ABV ", " 12oz serving"]
    ["Anchor Porter   ", " 5.6% ABV ", " 12oz serving"]
    ["Anchor Steam   ", " 4.9% ABV ", " 12oz serving"]
    ["Angry Orchard Traditional Dry Cider ", " 5.5% ABV ", " 12oz serving"]
    ["Arbor Mist White Zinfandel Exotic Fruit ", " 6% ABV ", " 5oz serving"]
    ["Asahi Black   ", " 5.3% ABV ", " 12oz serving"]
    ["Asahi Super Dry   ", " 4.9% ABV ", " 12oz serving"]
    ["Bacardi 151 Rum   ", " 75.5% ABV ", " 1.5oz serving"]
    ["Bacardi Gold Rum   ", " 40% ABV ", " 1.5oz serving"]
    ["Bacardi Light Mojito   ", " 12.5% ABV ", " 12oz serving"]
    ["Bacardi Light Pina Colada   ", " 11.5% ABV ", " 12oz serving"]
    ["Bacardi Silver 03   ", " 5% ABV ", " 12oz serving"]
    ["Bacardi Silver Mojito   ", " 5% ABV ", " 12oz serving"]
    ["Bacardi Silver Peach   ", " 5% ABV ", " 12oz serving"]
    ["Baily's Irish Cream ", " 17% ABV ", " 1.5oz serving"]
    ["Ballarat Bitter ", " 4.6% ABV ", " 12oz serving"]
    ["Bards Original Sorghum Malt Beer ", " 4.6% ABV ", " 12oz serving"]
    ["Bass   ", " 5.1% ABV ", " 12oz serving"]
    ["Batch 19 ", " 5.5% ABV ", " 12oz serving"]
    ["Becherovka ", " 38% ABV ", " 1.5oz serving"]
    ["Beck's Dark   ", " 5% ABV ", " 12oz serving"]
    ["Beck's Octoberfest   ", " 5.2% ABV ", " 12oz serving"]
    ["Beck's Premier Light   ", " 2.3% ABV ", " 12oz serving"]
    ["Becks Pilsner   ", " 5% ABV ", " 12oz serving"]
    ["Becks Sapphire   ", " 6% ABV ", " 12oz serving"]
    ["Beefeater Gin ", " 47% ABV ", " 1.5oz serving"]
    ["Beez Neez (Matilda Bay) ", " 4.7% ABV ", " 12oz serving"]
    ["Belle-Vue Selection Lambic   ", " 6% ABV ", " 12oz serving"]
    ["Big Flats Lager Beer ", " 4.5% ABV ", " 12oz serving"]
    ["Big Flats Light Beer ", " 3.9% ABV ", " 12oz serving"]
    ["Bitburger Light   ", " 2.8% ABV ", " 12oz serving"]
    ["Blackthorn Cider ", " 4.7% ABV ", " 12oz serving"]
    ["Bloody Mary ", " 8% ABV ", " 12oz serving"]
    ["Blue Moon Belgian White   ", " 5.4% ABV ", " 12oz serving"]
    ["Blue Moon Full Moon Winter Ale ", " 5.52% ABV ", " 12oz serving"]
    ["Blue Moon Harvest Moon Pumpkin Ale ", " 5.76% ABV ", " 12oz serving"]
    ["Blue Moon Honey Moon Summer Ale ", " 5.2% ABV ", " 12oz serving"]
    ["Blue Moon Rising Moon Spring Ale ", " 5.4% ABV ", " 12oz serving"]
    ["Blue Paddle Pilsner Lager   ", " 4.8% ABV ", " 12oz serving"]
    ["Boags Draught   ", " 4.6% ABV ", " 12oz serving"]
    ["Boags XXX Ale   ", " 4.8% ABV ", " 12oz serving"]
    ["Boddingtons Pub Ale   ", " 4.6% ABV ", " 12oz serving"]
    ["Bohemia Clasica ", " 5.3% ABV ", " 12oz serving"]
    ["Bombay Sapphire Gin    ", " 47% ABV ", " 1.5oz serving"]
    ["Bowman's Vodka ", " 40% ABV ", " 1.5oz serving"]
    ["Bud American Ale   ", " 5.3% ABV ", " 12oz serving"]
    ["Bud Dry   ", " 5% ABV ", " 12oz serving"]
    ["Bud Ice   ", " 5.5% ABV ", " 12oz serving"]
    ["Bud Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Bud Light Golden Wheat   ", " 4.1% ABV ", " 12oz serving"]
    ["Bud Light Lime   ", " 4.2% ABV ", " 12oz serving"]
    ["Bud Light Lime-A-Rita 6%   ", " 6% ABV ", " 12oz serving"]
    ["Bud Light Lime-A-Rita 8%   ", " 8% ABV ", " 12oz serving"]
    ["Bud Light Platinum    ", " 6% ABV ", " 12oz serving"]
    ["Bud Select 55    ", " 2.4% ABV ", " 12oz serving"]
    ["Budweiser   ", " 5% ABV ", " 12oz serving"]
    ["Budweiser Black Crown ", " 6% ABV ", " 12oz serving"]
    ["Budweiser Select   ", " 4.3% ABV ", " 12oz serving"]
    ["Bulleit Bourbon ", " 45% ABV ", " 1.5oz serving"]
    ["Bulleit Rye ", " 45% ABV ", " 1.5oz serving"]
    ["Bulmers Irish Cider ", " 4.5% ABV ", " 12oz serving"]
    ["Bulmers Light Irish Cider ", " 4.5% ABV ", " 12oz serving"]
    ["Busch   ", " 4.3% ABV ", " 12oz serving"]
    ["Busch Ice   ", " 5.9% ABV ", " 12oz serving"]
    ["Busch Light   ", " 4.1% ABV ", " 12oz serving"]
    ["Busch NA  ", " 0.4% ABV ", " 12oz serving"]
    ["Bushmills Irish Whiskey ", " 40% ABV ", " 1.5oz serving"]
    ["Cabernet Sauvignon    ", " 13.8% ABV ", " 5oz serving"]
    ["Captain Morgan - Long Island Iced Tea ", " 17% ABV ", " 1.5oz serving"]
    ["Captain Morgan - Private Stock 40% ", " 40% ABV ", " 1.5oz serving"]
    ["Captain Morgan 100 Proof Rum ", " 50% ABV ", " 1.5oz serving"]
    ["Captain Morgan Black Spiced Rum ", " 47.3% ABV ", " 1.5oz serving"]
    ["Captain Morgan Original Spiced Rum   ", " 35% ABV ", " 1.5oz serving"]
    ["Carling   ", " 4% ABV ", " 12oz serving"]
    ["Carling Chrome   ", " 4.8% ABV ", " 12oz serving"]
    ["Carlo Rossi - Blush ", " 9.1% ABV ", " 5oz serving"]
    ["Carlo Rossi - Burgundy   ", " 12.5% ABV ", " 5oz serving"]
    ["Carlo Rossi - Cabernet Sauvignon   ", " 11.8% ABV ", " 5oz serving"]
    ["Carlo Rossi - Chablis ", " 10.2% ABV ", " 5oz serving"]
    ["Carlo Rossi - Chianti ", " 12.4% ABV ", " 5oz serving"]
    ["Carlo Rossi - Paisano ", " 11.9% ABV ", " 5oz serving"]
    ["Carlo Rossi - Rhine ", " 9.2% ABV ", " 5oz serving"]
    ["Carlo Rossi - Sangria Spanada ", " 10% ABV ", " 5oz serving"]
    ["Carlo Rossi - Vin Rose ", " 9.1% ABV ", " 5oz serving"]
    ["Carlo Rossi - White Grenache ", " 10.5% ABV ", " 5oz serving"]
    ["Carlo Rossi - White Zinfandel ", " 8% ABV ", " 5oz serving"]
    ["Carlsberg Elephant   ", " 7.2% ABV ", " 12oz serving"]
    ["Carlsberg Export   ", " 5% ABV ", " 12oz serving"]
    ["Cascade Lager   ", " 4.8% ABV ", " 12oz serving"]
    ["Cascade Premium Light   ", " 2.6% ABV ", " 12oz serving"]
    ["Chambord Black Raspberry Liqueur   ", " 16.5% ABV ", " 1.5oz serving"]
    ["Chambord Flavored Vodka   ", " 37.5% ABV ", " 1.5oz serving"]
    ["Champagne - Dom Perignon (Year 2000)   ", " 12.5% ABV ", " 5oz serving"]
    ["Champagne - Moet Imperial (White Star)   ", " 12.5% ABV ", " 5oz serving"]
    ["Chardonnay (Sterling Vineyards)  ", " 14.4% ABV ", " 5oz serving"]
    ["Charles Shaw - Cabernet Sauvignon ", " 12.5% ABV ", " 5oz serving"]
    ["Chelada Bud Light ", " 4.2% ABV ", " 12oz serving"]
    ["Chelada Budweiser   ", " 5% ABV ", " 12oz serving"]
    ["Chianti - Davinci   ", " 13% ABV ", " 5oz serving"]
    ["Chimay Rouge   ", " 7% ABV ", " 12oz serving"]
    ["Chimay Triple   ", " 8% ABV ", " 12oz serving"]
    ["Chivas Regal Premium Scotch Whisky  ", " 40% ABV ", " 1.5oz serving"]
    ["Cointreau Triple Sec ", " 40% ABV ", " 1.5oz serving"]
    ["Colt 45 Malt Liquor   ", " 6.1% ABV ", " 12oz serving"]
    ["Coors Banquet   ", " 5% ABV ", " 12oz serving"]
    ["Coors Extra Gold Lager   ", " 5% ABV ", " 12oz serving"]
    ["Coors Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Coors Non-Alcoholic   ", " 0.5% ABV ", " 12oz serving"]
    ["Corona Extra   ", " 4.6% ABV ", " 12oz serving"]
    ["Corona Light   ", " 4.1% ABV ", " 12oz serving"]
    ["Corona Premier ", " 4% ABV ", " 12oz serving"]
    ["Coronado Brewing Orange Ave Wit   ", " 5.2% ABV ", " 12oz serving"]
    ["Coronado Golden - Coronado Brewing Co.   ", " 5.4% ABV ", " 12oz serving"]
    ["Coronado Idiot IPA   ", " 8.5% ABV ", " 12oz serving"]
    ["Cosmopolitan   ", " 22.9% ABV ", " 3.5oz serving"]
    ["Courvoisier XO Cognac ", " 40% ABV ", " 1.5oz serving"]
    ["Cragganmore Scotch Whisky ", " 60.1% ABV ", " 1.5oz serving"]
    ["Cranberry Vodka (Cape Cod)   ", " 10.91% ABV ", " 12oz serving"]
    ["Creme de menthe ", " 36% ABV ", " 1.5oz serving"]
    ["Crispin Natural Hard Apple Cider ", " 6.9% ABV ", " 12oz serving"]
    ["Cristal ", " 4.6% ABV ", " 12oz serving"]
    ["Crown Gold   ", " 3.5% ABV ", " 12oz serving"]
    ["Crown Lager   ", " 4.9% ABV ", " 12oz serving"]
    ["Crown Royal - Special Reserve   ", " 40% ABV ", " 1.5oz serving"]
    ["Dalwhinnie Scotch Whisky ", " 57.8% ABV ", " 1.5oz serving"]
    ["Disaronno - Amaretto Di Saronno ", " 28% ABV ", " 1.5oz serving"]
    ["Dogfish Head 60min IPA   ", " 6% ABV ", " 12oz serving"]
    ["Don Julio Blanco Tequila ", " 40% ABV ", " 1.5oz serving"]
    ["Dos Equis Amber   ", " 4.6% ABV ", " 12oz serving"]
    ["Dos Equis Lager   ", " 4.6% ABV ", " 12oz serving"]
    ["Dry Blackthorn Cider ", " 5% ABV ", " 12oz serving"]
    ["Dunkelweisse   ", " 5.5% ABV ", " 12oz serving"]
    ["Duvel   ", " 8.5% ABV ", " 12oz serving"]
    ["E & J Brandy VSOP ", " 40% ABV ", " 1.5oz serving"]
    ["E&J Brandy ", " 40% ABV ", " 1.5oz serving"]
    ["E&J Cognac ", " 40% ABV ", " 1.5oz serving"]
    ["E&J XO Brandy ", " 40% ABV ", " 1.5oz serving"]
    ["Emu Bitter   ", " 4% ABV ", " 12oz serving"]
    ["Emu Draft   ", " 3% ABV ", " 12oz serving"]
    ["Exotic Berry - Bartles & Jaymes ", " 3.6% ABV ", " 12oz serving"]
    ["Fat Tire   ", " 5.2% ABV ", " 12oz serving"]
    ["Fireball Whisky ", " 33% ABV ", " 1.5oz serving"]
    ["Foster's   ", " 5% ABV ", " 12oz serving"]
    ["Fosters Premium Ale   ", " 5.5% ABV ", " 12oz serving"]
    ["Four Loko (all flavors)   ", " 12% ABV ", " 12oz serving"]
    ["Franzia Cabernet Sauvingon    ", " 12% ABV ", " 5oz serving"]
    ["Franzia Chillable Red ", " 9% ABV ", " 5oz serving"]
    ["Franzia Crisp White Wine ", " 9% ABV ", " 5oz serving"]
    ["Franzia Merlot Wine ", " 12.5% ABV ", " 5oz serving"]
    ["Franzia Shiraz Wine ", " 13% ABV ", " 5oz serving"]
    ["Frederick Miller Classic Chocolate Lager   ", " 5.5% ABV ", " 12oz serving"]
    ["Fuzzy Navel - Bartles & Jaymes ", " 3.6% ABV ", " 12oz serving"]
    ["Gaymers Berry Cider ", " 3.8% ABV ", " 12oz serving"]
    ["Gaymers Original Cider ", " 4.5% ABV ", " 12oz serving"]
    ["Gaymers Pear Cider ", " 4.5% ABV ", " 12oz serving"]
    ["George Killian's Irish Red   ", " 5.4% ABV ", " 12oz serving"]
    ["Gewurztraminer Wine   ", " 12% ABV ", " 5oz serving"]
    ["Gin and Tonic ", " 10% ABV ", " 12oz serving"]
    ["Girl Go Lightly Rose Wine ", " 11% ABV ", " 5oz serving"]
    ["Glenfiddich Scotch Whisky ", " 40% ABV ", " 1.5oz serving"]
    ["Godiva - Chocolate Cream Liqueur ", " 15% ABV ", " 1.5oz serving"]
    ["Goldschlager ", " 43.5% ABV ", " 1.5oz serving"]
    ["Goose Island Honkers Ale ", " 4.3% ABV ", " 12oz serving"]
    ["Goose Island India Pale Ale ", " 5.9% ABV ", " 12oz serving"]
    ["Goose Island Nut Brown Ale ", " 5.4% ABV ", " 12oz serving"]
    ["Goose Island Oktoberfest ", " 6.4% ABV ", " 12oz serving"]
    ["Goose Island Ten Hills Pale Ale ", " 6.2% ABV ", " 12oz serving"]
    ["Gordons - Dry Gin ", " 40% ABV ", " 1.5oz serving"]
    ["Grahams 2007 Vintage Port ", " 20% ABV ", " 5oz serving"]
    ["Grand Marnier Orange Liqueur ", " 40% ABV ", " 1.5oz serving"]
    ["Grand Monarch ", " 40% ABV ", " 1.5oz serving"]
    ["Greens Premium Golden Ale ", " 4.8% ABV ", " 12oz serving"]
    ["Greens Premium Pils ", " 4.8% ABV ", " 12oz serving"]
    ["Greens Tripel Blonde Ale   ", " 8.5% ABV ", " 12oz serving"]
    ["Grey Goose Vodka   ", " 40% ABV ", " 1.5oz serving"]
    ["Grolsch Amber Ale   ", " 5.4% ABV ", " 12oz serving"]
    ["Grolsch Blonde Lager    ", " 2.8% ABV ", " 12oz serving"]
    ["Grolsch Light Lager    ", " 3.6% ABV ", " 12oz serving"]
    ["Grolsch Premium Lager    ", " 5% ABV ", " 12oz serving"]
    ["Guinness Black Lager ", " 4.5% ABV ", " 12oz serving"]
    ["Guinness Blonde American Lager ", " 5% ABV ", " 12oz serving"]
    ["Guinness Draught   ", " 4.2% ABV ", " 12oz serving"]
    ["Guinness Generous Ale ", " 5.6% ABV ", " 12oz serving"]
    ["Hahn Premium   ", " 5% ABV ", " 12oz serving"]
    ["Hahn Premium Light   ", " 2.6% ABV ", " 12oz serving"]
    ["Hakutsuru Draft Sake ", " 14% ABV ", " 12oz serving"]
    ["Hakutsuru Plum Wine ", " 12.5% ABV ", " 5oz serving"]
    ["Hakutsuru Plum Wine Slim ", " 10.5% ABV ", " 5oz serving"]
    ["Hakutsuru Premium Sake ", " 15.5% ABV ", " 5oz serving"]
    ["Hakutsuru Superior Sake ", " 14.5% ABV ", " 5oz serving"]
    ["Hamm's   ", " 4.7% ABV ", " 12oz serving"]
    ["Hamm's Special Light   ", " 3.9% ABV ", " 12oz serving"]
    ["Harbin Lager  ↵ ", " 4.8% ABV ", " 12oz serving"]
    ["Harp Lager   ", " 4.7% ABV ", " 12oz serving"]
    ["Heineken   ", " 5% ABV ", " 12oz serving"]
    ["Heineken Light   ", " 3.5% ABV ", " 12oz serving"]
    ["Hendricks Gin ", " 44% ABV ", " 1.5oz serving"]
    ["Henry Weinhard's Belgian Style Wheat   ", " 4.9% ABV ", " 12oz serving"]
    ["Henry Weinhard's Blonde   ", " 5.1% ABV ", " 12oz serving"]
    ["Henry Weinhard's Blue Boar   ", " 4.6% ABV ", " 12oz serving"]
    ["Henry Weinhard's Classic Dark Lager   ", " 5% ABV ", " 12oz serving"]
    ["Henry Weinhard's Hefeweizen   ", " 4.9% ABV ", " 12oz serving"]
    ["Henry Weinhard's India Pale Ale   ", " 6% ABV ", " 12oz serving"]
    ["Henry Weinhard's Private Reserve   ", " 4.8% ABV ", " 12oz serving"]
    ["Hoegaarden White   ", " 4.9% ABV ", " 12oz serving"]
    ["Hornsby's Hard Cider - Draft Cider ", " 6% ABV ", " 12oz serving"]
    ["Hornsby's Hard Cider - Hard Apple Cider ", " 5.5% ABV ", " 12oz serving"]
    ["Hpnotiq ", " 17% ABV ", " 1.5oz serving"]
    ["HRD Peach Schnapps ", " 21% ABV ", " 1.5oz serving"]
    ["HRD Root Beer Schnapps ", " 21% ABV ", " 1.5oz serving"]
    ["Hurricane (Original)   ", " 6% ABV ", " 12oz serving"]
    ["Hurricane High Gravity   ", " 8.1% ABV ", " 12oz serving"]
    ["Hurricane Ice   ", " 7.5% ABV ", " 12oz serving"]
    ["Icehouse    ", " 5.5% ABV ", " 12oz serving"]
    ["Imperial   ", " 4.6% ABV ", " 12oz serving"]
    ["Irish Car Bomb   ", " 6.9% ABV ", " 12oz serving"]
    ["Jack and Coke   ", " 10% ABV ", " 12oz serving"]
    ["Jack and Diet Coke   ", " 10% ABV ", " 12oz serving"]
    ["Jack Daniels Whiskey   ", " 40% ABV ", " 1.5oz serving"]
    ["Jager Bomb   ", " 8.75% ABV ", " 6oz serving"]
    ["Jagermeister   ", " 35% ABV ", " 1.5oz serving"]
    ["James Boags Premium   ", " 5% ABV ", " 12oz serving"]
    ["James Boags Premium Light   ", " 2.9% ABV ", " 12oz serving"]
    ["Jameson Irish Whiskey ", " 40% ABV ", " 1.5oz serving"]
    ["Jeremiah Weed - Lightning Lemonade ", " 5.8% ABV ", " 12oz serving"]
    ["Jeremiah Weed - Roadhouse Tea ", " 5.8% ABV ", " 12oz serving"]
    ["Jeremiah Weed - Spiked Cola  ", " 5.8% ABV ", " 12oz serving"]
    ["Jeremiah Weed Bourbon ", " 50% ABV ", " 1.5oz serving"]
    ["Jeremiah Weed Sweet Tea  ", " 35% ABV ", " 1.5oz serving"]
    ["Jim Beam Kentuckty Straight Bourbon Whiskey ", " 40% ABV ", " 1.5oz serving"]
    ["Johnnie Walker - Red Label 43% ", " 43% ABV ", " 1.5oz serving"]
    ["Jose Cuervo - Golden Margarita Pre mixed ", " 12.7% ABV ", " 12oz serving"]
    ["Jose Cuervo Especial (Gold)   ", " 40% ABV ", " 1.5oz serving"]
    ["Jose Cuervo Especial (Silver)   ", " 40% ABV ", " 1.5oz serving"]
    ["Jose Cuervo Light Margarita ", " 9.95% ABV ", " 12oz serving"]
    ["K Cider (UK version) ", " 8.35% ABV ", " 12oz serving"]
    ["Kahlua   ", " 20% ABV ", " 1.5oz serving"]
    ["Kamikaze ", " 28.6% ABV ", " 3.5oz serving"]
    ["Karl Strauss - Amber Lager   ", " 4.2% ABV ", " 12oz serving"]
    ["Karl Strauss - Red Trolley Ale   ", " 5.8% ABV ", " 12oz serving"]
    ["Ketel One Vodka     ", " 40% ABV ", " 1.5oz serving"]
    ["Keystone Ice   ", " 5.9% ABV ", " 12oz serving"]
    ["Keystone Light   ", " 4.13% ABV ", " 12oz serving"]
    ["Keystone Premium   ", " 4.43% ABV ", " 12oz serving"]
    ["King Cobra  ", " 6% ABV ", " 12oz serving"]
    ["Kirin Free ", " 0% ABV ", " 12oz serving"]
    ["Kirin Ichiban   ", " 4.9% ABV ", " 12oz serving"]
    ["Kirin Light   ", " 3.2% ABV ", " 12oz serving"]
    ["Knob Creek Bourbon ", " 50% ABV ", " 1.5oz serving"]
    ["Kona Big Wave Golden Ale ", " 4.4% ABV ", " 12oz serving"]
    ["Kona Fire Rock Pale Ale ", " 6% ABV ", " 12oz serving"]
    ["Kona Koko Nut Brown Ale ", " 5.5% ABV ", " 12oz serving"]
    ["Kona Longboard Island Lager ", " 4.6% ABV ", " 12oz serving"]
    ["Kona Pipeline Porter ", " 5.3% ABV ", " 12oz serving"]
    ["Kona Wailua Wheat Ale ", " 5.4% ABV ", " 12oz serving"]
    ["Konig Pilsener   ", " 4.9% ABV ", " 12oz serving"]
    ["Konig Radler   ", " 2.5% ABV ", " 12oz serving"]
    ["Krombacher Dark   ", " 4.3% ABV ", " 12oz serving"]
    ["Krombacher Pils   ", " 4.8% ABV ", " 12oz serving"]
    ["Krombacher Weizen   ", " 5.3% ABV ", " 12oz serving"]
    ["Kronenbourg 1664   ", " 5.5% ABV ", " 12oz serving"]
    ["Labatt Blue   ", " 5% ABV ", " 12oz serving"]
    ["Labatt Blue Light   ", " 4% ABV ", " 12oz serving"]
    ["Labatt Sterling   ", " 4% ABV ", " 12oz serving"]
    ["Landshark Lager   ", " 4.6% ABV ", " 12oz serving"]
    ["Leffe Tripel   ", " 8.5% ABV ", " 12oz serving"]
    ["Leinenkugel's Berry Weiss   ", " 4.7% ABV ", " 12oz serving"]
    ["Leinenkugel's BIG BUTT Dopplebock   ", " 5.8% ABV ", " 12oz serving"]
    ["Leinenkugel's Creamy Dark   ", " 4.9% ABV ", " 12oz serving"]
    ["Leinenkugel's Fireside Nut Brown   ", " 4.9% ABV ", " 12oz serving"]
    ["Leinenkugel's Honey Weiss   ", " 4.9% ABV ", " 12oz serving"]
    ["Leinenkugel's Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Leinenkugel's Oktoberfest Lager   ", " 5.1% ABV ", " 12oz serving"]
    ["Leinenkugel's Original Lager   ", " 4.7% ABV ", " 12oz serving"]
    ["Leinenkugel's Red Lager   ", " 4.9% ABV ", " 12oz serving"]
    ["Leinenkugel's Summer Shandy   ", " 4.2% ABV ", " 12oz serving"]
    ["Leinenkugel's Sunset Wheat   ", " 4.9% ABV ", " 12oz serving"]
    ["Licher Pilsner Leicht   ", " 2.8% ABV ", " 12oz serving"]
    ["Limoncello ", " 32% ABV ", " 1.5oz serving"]
    ["Long Island Iced Tea ", " 23.8% ABV ", " 12oz serving"]
    ["Lowenbrau Dark   ", " 5% ABV ", " 12oz serving"]
    ["Lowenbrau Special Beer   ", " 5.2% ABV ", " 12oz serving"]
    ["Lucid Absinthe Superieure ", " 62% ABV ", " 1.5oz serving"]
    ["Magners Golden Draught ", " 4.5% ABV ", " 12oz serving"]
    ["Magners Irish Cider ", " 4.5% ABV ", " 12oz serving"]
    ["Magners Original Cider (UK varient) ", " 4.5% ABV ", " 12oz serving"]
    ["Magners Pear and Ginger ", " 4% ABV ", " 12oz serving"]
    ["Magners Pear Cider ", " 4.5% ABV ", " 12oz serving"]
    ["Magners Spiced Apple and Honey ", " 4% ABV ", " 12oz serving"]
    ["Magnum Malt Liquor   ", " 5.6% ABV ", " 12oz serving"]
    ["Makers Mark   ", " 45.5% ABV ", " 1.5oz serving"]
    ["Malibu Rum   ", " 21% ABV ", " 1.5oz serving"]
    ["Margarita ", " 10% ABV ", " 12oz serving"]
    ["Margarita - Bartles & Jaymes ", " 3.6% ABV ", " 12oz serving"]
    ["MARTINI & ROSSI Asti ", " 7% ABV ", " 5oz serving"]
    ["MARTINI & ROSSI Extra Dry ", " 18% ABV ", " 5oz serving"]
    ["MARTINI & ROSSI Prosecco ", " 10.5% ABV ", " 5oz serving"]
    ["Martini   ", " 43.1% ABV ", " 4oz serving"]
    ["Merlot   ", " 13.9% ABV ", " 5oz serving"]
    ["MGD 64 Lemonade   ", " 2.8% ABV ", " 12oz serving"]
    ["Michelob   ", " 4.8% ABV ", " 12oz serving"]
    ["Michelob AmberBock   ", " 5.1% ABV ", " 12oz serving"]
    ["Michelob Honey Lager  ↵ ", " 4.9% ABV ", " 12oz serving"]
    ["Michelob Light   ", " 4.1% ABV ", " 12oz serving"]
    ["Michelob Ultra 19th Hole Light Tea & Lemonade   ", " 3.9% ABV ", " 12oz serving"]
    ["Michelob Ultra   ", " 4.2% ABV ", " 12oz serving"]
    ["Michelob Ultra Amber   ", " 4% ABV ", " 12oz serving"]
    ["Michelob ULTRA Dragonfruit Peach ", " 4% ABV ", " 12oz serving"]
    ["Michelob Ultra Light Cider   ", " 4% ABV ", " 12oz serving"]
    ["Michelob ULTRA Lime Cactus ", " 4% ABV ", " 12oz serving"]
    ["Michelob ULTRA Pomegranate Raspberry ", " 4% ABV ", " 12oz serving"]
    ["Mickey's Fine Malt Liquor   ", " 5.6% ABV ", " 12oz serving"]
    ["Mickey's Ice   ", " 5.8% ABV ", " 12oz serving"]
    ["Midori ", " 20% ABV ", " 1.5oz serving"]
    ["Mike's Hard Lemonade   ", " 5% ABV ", " 12oz serving"]
    ["Mike's Lite Hard Lemonade   ", " 3.2% ABV ", " 12oz serving"]
    ["Miller Chill   ", " 4.2% ABV ", " 12oz serving"]
    ["Miller Fortune ", " 6.9% ABV ", " 12oz serving"]
    ["Miller Genuine Draft   ", " 4.6% ABV ", " 12oz serving"]
    ["Miller Genuine Draft Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Miller High Life   ", " 4.6% ABV ", " 12oz serving"]
    ["Miller High Life Light   ", " 4.1% ABV ", " 12oz serving"]
    ["Miller Icehouse Light   ", " 4.13% ABV ", " 12oz serving"]
    ["Miller Lite   ", " 4.2% ABV ", " 12oz serving"]
    ["Miller64   ", " 2.8% ABV ", " 12oz serving"]
    ["Milwaukee's Best Ice   ", " 5.9% ABV ", " 12oz serving"]
    ["Milwaukee's Best Light   ", " 4.1% ABV ", " 12oz serving"]
    ["Milwaukee's Best Premium   ", " 4.3% ABV ", " 12oz serving"]
    ["Mimosa    ", " 6.25% ABV ", " 5oz serving"]
    ["Modelo Especial   ", " 4.4% ABV ", " 12oz serving"]
    ["Mojito   ", " 6.3% ABV ", " 12oz serving"]
    ["Molson Canadian    ", " 5% ABV ", " 12oz serving"]
    ["Molson Canadian 67    ", " 3% ABV ", " 12oz serving"]
    ["Molson Canadian Light    ", " 3.9% ABV ", " 12oz serving"]
    ["Molson Golden    ", " 5% ABV ", " 12oz serving"]
    ["Molson Ice    ", " 5.6% ABV ", " 12oz serving"]
    ["Molson XXX    ", " 7.3% ABV ", " 12oz serving"]
    ["Monarch 151 Rum ", " 75.5% ABV ", " 1.5oz serving"]
    ["Monarch Brandy ", " 40% ABV ", " 1.5oz serving"]
    ["Monarch Citron Vodka ", " 35% ABV ", " 1.5oz serving"]
    ["Monarch Pineapple Rum ", " 21% ABV ", " 1.5oz serving"]
    ["Moscato (Girl Go Lightly 2012) ", " 11% ABV ", " 5oz serving"]
    ["Murphys Irish Stout ", " 4% ABV ", " 12oz serving"]
    ["Myers Frozen Pina Colada ", " 13% ABV ", " 5oz serving"]
    ["Myers Frozen Strawberry Daiquiri ", " 13% ABV ", " 5oz serving"]
    ["Myers Original Dark Rum ", " 40% ABV ", " 1.5oz serving"]
    ["Natty Daddy   ", " 8% ABV ", " 12oz serving"]
    ["Natural Ice   ", " 5.9% ABV ", " 12oz serving"]
    ["Natural Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Negra Modelo   ", " 5.4% ABV ", " 12oz serving"]
    ["New Belgium Sunshine Wheat   ", " 4.8% ABV ", " 12oz serving"]
    ["New Planet 3R Raspberry Ale ", " 5% ABV ", " 12oz serving"]
    ["New Planet Off Grid Pale Ale ", " 5% ABV ", " 12oz serving"]
    ["O'Doul's   ", " 0.4% ABV ", " 12oz serving"]
    ["ODouls Amber  ", " 0.4% ABV ", " 12oz serving"]
    ["Old Milwaukee Beer   ", " 4.5% ABV ", " 12oz serving"]
    ["Old Milwaukee Light   ", " 3.8% ABV ", " 12oz serving"]
    ["Olde English 800 7.5   ", " 7.5% ABV ", " 12oz serving"]
    ["Olde English 800   ", " 5.9% ABV ", " 12oz serving"]
    ["Olde English High Gravity 800   ", " 8% ABV ", " 12oz serving"]
    ["Ozeki Sake (Regular Type) ", " 16% ABV ", " 5oz serving"]
    ["Pabst Blue Ribbon   ", " 4.74% ABV ", " 12oz serving"]
    ["Pabst Blue Ribbon Light ", " 4.19% ABV ", " 12oz serving"]
    ["Pacifico   ", " 4.4% ABV ", " 12oz serving"]
    ["Parrot Bay Caribbean Coconut Rum ", " 20% ABV ", " 1.5oz serving"]
    ["Pastis pure ", " 45% ABV ", " 1.5oz serving"]
    ["Patron Anejo Tequila   ", " 40% ABV ", " 1.5oz serving"]
    ["Patron Gran Patron Burdeos Anejo ", " 40% ABV ", " 1.5oz serving"]
    ["Patron Silver Tequila    ", " 40% ABV ", " 1.5oz serving"]
    ["Paulaner Hefe-Weizen   ", " 5.5% ABV ", " 12oz serving"]
    ["Paulaner Munich Premium Lager   ", " 4.9% ABV ", " 12oz serving"]
    ["Paulaner Oktoberfest Marzen    ", " 5.8% ABV ", " 12oz serving"]
    ["Pendleton Whisky ", " 40% ABV ", " 1.5oz serving"]
    ["Peroni Nastro Azzurro   ", " 5.1% ABV ", " 12oz serving"]
    ["Pete's Wicked Ale   ", " 5.3% ABV ", " 12oz serving"]
    ["Pig's Eye Ice Beer   ", " 5.9% ABV ", " 12oz serving"]
    ["Pig's Eye Lean Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Pilsner Urquell   ", " 4.4% ABV ", " 12oz serving"]
    ["Pina Colada (blended) ", " 10% ABV ", " 12oz serving"]
    ["Pina Colada - Bartles & Jaymes ", " 3.6% ABV ", " 12oz serving"]
    ["Pinot Noir (Beaulieu Vineyard) ", " 13.7% ABV ", " 5oz serving"]
    ["Popov Vodka 100 proof ", " 50% ABV ", " 1.5oz serving"]
    ["Popov Vodka 80 proof ", " 40% ABV ", " 1.5oz serving"]
    ["Pyramid Apricot Ale ", " 5.1% ABV ", " 12oz serving"]
    ["Pyramid Hefeweizen   ", " 5.2% ABV ", " 12oz serving"]
    ["Pyramid Outburst IPA ", " 8.5% ABV ", " 12oz serving"]
    ["Pyramid ThunderHead IPA ", " 6.7% ABV ", " 12oz serving"]
    ["Red Bridge Beer ", " 4% ABV ", " 12oz serving"]
    ["Red Dog   ", " 4.8% ABV ", " 12oz serving"]
    ["Red Hook ESB   ", " 5.77% ABV ", " 12oz serving"]
    ["Red Hook IPA    ", " 6.5% ABV ", " 12oz serving"]
    ["Red Stripe   ", " 4.7% ABV ", " 12oz serving"]
    ["Red Stripe Light ", " 3.6% ABV ", " 12oz serving"]
    ["Redds Apple Ale ", " 5% ABV ", " 12oz serving"]
    ["Rolling Rock Extra Pale   ", " 4.5% ABV ", " 12oz serving"]
    ["Rum and Coke   ", " 8.75% ABV ", " 12oz serving"]
    ["Rum and Diet Coke    ", " 8.75% ABV ", " 12oz serving"]
    ["Rumple Minze - Peppermint  ", " 50% ABV ", " 1.5oz serving"]
    ["Sailor Jerry Spiced Navy Rum  ", " 46% ABV ", " 1.5oz serving"]
    ["Sam Adams Light   ", " 4% ABV ", " 12oz serving"]
    ["Sambuca Romana ", " 42% ABV ", " 1.5oz serving"]
    ["Samuel Adams Boston Ale   ", " 5.4% ABV ", " 12oz serving"]
    ["Samuel Adams Boston Lager    ", " 4.9% ABV ", " 12oz serving"]
    ["Samuel Adams Cherry Wheat   ", " 5.3% ABV ", " 12oz serving"]
    ["Samuel Adams Chocolate Bock   ", " 5.8% ABV ", " 12oz serving"]
    ["Samuel Adams Cream Stout   ", " 4.9% ABV ", " 12oz serving"]
    ["Samuel Adams Double Bock   ", " 9.5% ABV ", " 12oz serving"]
    ["Samuel Adams Noble Pils   ", " 4.9% ABV ", " 12oz serving"]
    ["Samuel Adams Pale Ale   ", " 5.4% ABV ", " 12oz serving"]
    ["Samuel Adams Winter Lager   ", " 5.6% ABV ", " 12oz serving"]
    ["Sapporo Premium   ", " 4.9% ABV ", " 12oz serving"]
    ["Sapporo Premium Light ", " 3.9% ABV ", " 12oz serving"]
    ["Sauvingnon Blanc    ", " 13.3% ABV ", " 5oz serving"]
    ["Sayuri Nigori Sake ", " 12.5% ABV ", " 5oz serving"]
    ["Schlitz Beer   ", " 4.7% ABV ", " 12oz serving"]
    ["Schlitz Light   ", " 4.2% ABV ", " 12oz serving"]
    ["Schlitz Malt Liquor   ", " 6.2% ABV ", " 12oz serving"]
    ["Screwdriver   ", " 13.3% ABV ", " 12oz serving"]
    ["Seagrams 7   ", " 40% ABV ", " 1.5oz serving"]
    ["Sharp's   ", " 0.4% ABV ", " 12oz serving"]
    ["Sheaf Stout   ", " 5.7% ABV ", " 12oz serving"]
    ["Shiner Blonde   ", " 4.4% ABV ", " 12oz serving"]
    ["Shiner Bock   ", " 4.4% ABV ", " 12oz serving"]
    ["Shiner Hefeweizen   ", " 5.4% ABV ", " 12oz serving"]
    ["Shiner Light   ", " 4% ABV ", " 12oz serving"]
    ["Shiner Light Blonde   ", " 4.2% ABV ", " 12oz serving"]
    ["Shock Top Belgian White   ", " 5.2% ABV ", " 12oz serving"]
    ["Shock Top Pumpkin   ", " 5.2% ABV ", " 12oz serving"]
    ["Shock Top Rasberry Wheat ", " 5.2% ABV ", " 12oz serving"]
    ["Sierra Nevada Bigfoot   ", " 9.6% ABV ", " 12oz serving"]
    ["Sierra Nevada Celebration Ale   ", " 6.8% ABV ", " 12oz serving"]
    ["Sierra Nevada Hoptimum ", " 10.4% ABV ", " 12oz serving"]
    ["Sierra Nevada Pale Ale   ", " 5.6% ABV ", " 12oz serving"]
    ["Sierra Nevada Summerfest Beer   ", " 5% ABV ", " 12oz serving"]
    ["Sierra Nevada Torpedo ", " 7.2% ABV ", " 12oz serving"]
    ["Sinfire Cinnamon Whisky ", " 39% ABV ", " 1.5oz serving"]
    ["Skinny Girl Margarita   ", " 12.7% ABV ", " 12oz serving"]
    ["Skinnygirl Bare Naked Vodka ", " 30% ABV ", " 1.5oz serving"]
    ["Skinnygirl Cucumber Vodka ", " 30% ABV ", " 1.5oz serving"]
    ["Skinnygirl Island Coconut Vodka ", " 30% ABV ", " 1.5oz serving"]
    ["Skinnygirl Pina Colada ", " 9.95% ABV ", " 12oz serving"]
    ["Skinnygirl Red Wine    ", " 12% ABV ", " 5oz serving"]
    ["Skinnygirl Rose Wine ", " 12% ABV ", " 5oz serving"]
    ["Skinnygirl Sangria ", " 10.5% ABV ", " 5oz serving"]
    ["Skinnygirl Tangerine Vodka ", " 30% ABV ", " 1.5oz serving"]
    ["Skinnygirl White Peach Margarita ", " 12.7% ABV ", " 12oz serving"]
    ["Skinnygirl White Wine ", " 12% ABV ", " 5oz serving"]
    ["Skol   ", " 4.7% ABV ", " 12oz serving"]
    ["Sleeman Clear   ", " 4% ABV ", " 12oz serving"]
    ["Smirnoff Ice ", " 5% ABV ", " 12oz serving"]
    ["Smirnoff Ice Light  ", " 3.2% ABV ", " 12oz serving"]
    ["Smirnoff Twist of Green Apple Vodka ", " 35% ABV ", " 1.5oz serving"]
    ["Smirnoff Twist of Raspberry Vodka ", " 35% ABV ", " 1.5oz serving"]
    ["Smirnoff Vodka Silver Label 90 Proof ", " 45.2% ABV ", " 1.5oz serving"]
    ["Smithwicks Draught    ", " 4.5% ABV ", " 12oz serving"]
    ["Southern Comfort (70 proof) ", " 35% ABV ", " 1.5oz serving"]
    ["Southwark Bitter   ", " 4.5% ABV ", " 12oz serving"]
    ["Sparks ", " 6% ABV ", " 12oz serving"]
    ["Sparks Blackberry ", " 8% ABV ", " 12oz serving"]
    ["Sparks Iced Tea   ", " 8% ABV ", " 12oz serving"]
    ["Sparks Lemonade   ", " 8% ABV ", " 12oz serving"]
    ["Sparks Light ", " 6% ABV ", " 12oz serving"]
    ["Sparks Plus 6% ", " 6% ABV ", " 12oz serving"]
    ["Sparks Plus 7% ", " 7% ABV ", " 12oz serving"]
    ["Spaten Lager   ", " 5.2% ABV ", " 12oz serving"]
    ["St. Pauli Girl - Lager   ", " 4.9% ABV ", " 12oz serving"]
    ["Steel Reserve High Gravity   ", " 8.1% ABV ", " 12oz serving"]
    ["Steel Six   ", " 6% ABV ", " 12oz serving"]
    ["Steinlager Classic   ", " 5% ABV ", " 12oz serving"]
    ["Stella Artois    ", " 5.2% ABV ", " 12oz serving"]
    ["Stella Rosa ", " 5.5% ABV ", " 5oz serving"]
    ["Stirrings Triple Sec ", " 30% ABV ", " 1.5oz serving"]
    ["Stolichnaya Vodka ", " 40% ABV ", " 1.5oz serving"]
    ["Strawberry Daiquiri (blended) ", " 9.36% ABV ", " 12oz serving"]
    ["Strawberry Daiquiri - Bartles & Jaymes ", " 3.6% ABV ", " 12oz serving"]
    ["Strohs   ", " 4.52% ABV ", " 12oz serving"]
    ["Strongbow Cider (USA variant)   ", " 5% ABV ", " 12oz serving"]
    ["Strongbow Dry Cider ", " 5% ABV ", " 12oz serving"]
    ["Swan Draught   ", " 4.5% ABV ", " 12oz serving"]
    ["Syrah Wine ", " 12.5% ABV ", " 5oz serving"]
    ["Tanqueray London Dry Gin    ", " 47.3% ABV ", " 1.5oz serving"]
    ["Tecate   ", " 4.25% ABV ", " 12oz serving"]
    ["Tennents Lager   ", " 4% ABV ", " 12oz serving"]
    ["Tennents Original Export Lager ", " 4.7% ABV ", " 12oz serving"]
    ["Tennents Special   ", " 3.5% ABV ", " 12oz serving"]
    ["Tennents Sweetheart Stout   ", " 2% ABV ", " 12oz serving"]
    ["Tequiza   ", " 4.5% ABV ", " 12oz serving"]
    ["TGIF - On The Rocks Mai Tai ", " 12.5% ABV ", " 12oz serving"]
    ["TGIF - On The Rocks Mudslide  ", " 10% ABV ", " 5oz serving"]
    ["TGIF - On The Rocks White Russian   ", " 12.5% ABV ", " 5oz serving"]
    ["Third Shift Amber Lager ", " 5.3% ABV ", " 12oz serving"]
    ["Three Olives Naked Vodka ", " 40% ABV ", " 1.5oz serving"]
    ["Tilt Green 10% ", " 10% ABV ", " 12oz serving"]
    ["Tilt Green 8% ", " 8% ABV ", " 12oz serving"]
    ["Tilt Orange 4.0% ABV ", " 4% ABV ", " 12oz serving"]
    ["Tilt Purple 12% ", " 12% ABV ", " 12oz serving"]
    ["Tilt Red 12% ", " 12% ABV ", " 12oz serving"]
    ["Tooheys New   ", " 4.6% ABV ", " 12oz serving"]
    ["Tooheys Old   ", " 4.4% ABV ", " 12oz serving"]
    ["Trippel Belgian Style Ale   ", " 7.8% ABV ", " 12oz serving"]
    ["Tsingtao   ", " 4.8% ABV ", " 12oz serving"]
    ["Tuaca Liqueur ", " 35% ABV ", " 1.5oz serving"]
    ["Tusker Lager ", " 4.2% ABV ", " 12oz serving"]
    ["Twisted Tea Light - Hard Iced Tea ", " 4% ABV ", " 12oz serving"]
    ["Tyskie ", " 5.6% ABV ", " 12oz serving"]
    ["ULLR Nodic Libation ", " 45% ABV ", " 1.5oz serving"]
    ["Valima Lager   ", " 4.9% ABV ", " 12oz serving"]
    ["Vermouth - Martini Rosso Vermouth   ", " 16% ABV ", " 1.5oz serving"]
    ["Victoria    ", " 4.04% ABV ", " 12oz serving"]
    ["Victoria Bitter   ", " 4.6% ABV ", " 12oz serving"]
    ["Vodka - Royal Gate (generic) 80 proof ", " 40% ABV ", " 1.5oz serving"]
    ["Vodka and Diet Coke   ", " 13.3% ABV ", " 12oz serving"]
    ["Vodka and Red Bull    ", " 13.3% ABV ", " 12oz serving"]
    ["Vodka and Red Bull Sugar Free   ", " 13.3% ABV ", " 12oz serving"]
    ["Vodka and Rockstar    ", " 13.3% ABV ", " 12oz serving"]
    ["Vodka and Rockstar Diet   ", " 13.3% ABV ", " 12oz serving"]
    ["Warsteiner Premium Dunkel   ", " 4.8% ABV ", " 12oz serving"]
    ["Warsteiner Premium Verum   ", " 4.8% ABV ", " 12oz serving"]
    ["West End Draught   ", " 4.5% ABV ", " 12oz serving"]
    ["White Russian   ", " 17.7% ABV ", " 5oz serving"]
    ["Wild Turkey 101 ", " 50.5% ABV ", " 1.5oz serving"]
    ["Wild Turkey 80 ", " 40% ABV ", " 1.5oz serving"]
    ["Wyder's Apple Cider ", " 5% ABV ", " 12oz serving"]
    ["Wyder's Pear Cider ", " 4% ABV ", " 12oz serving"]
    ["Wyder's Raspberry Cider ", " 4% ABV ", " 12oz serving"]
    ["XXXX Bitter   ", " 4.6% ABV ", " 12oz serving"]
    ["Yazi Ginger Vodka ", " 35% ABV ", " 1.5oz serving"]
    ["Yuengling Black & Tan   ", " 4.8% ABV ", " 12oz serving"]
    ["Yuengling Chesterfield Ale   ", " 5.2% ABV ", " 12oz serving"]
    ["Yuengling Lager   ", " 4.6% ABV ", " 12oz serving"]
    ["Yuengling Light Lager   ", " 3.5% ABV ", " 12oz serving"]
    ["Yuengling Porter   ", " 4.8% ABV ", " 12oz serving"]
    ["Yuengling Premium   ", " 4.6% ABV ", " 12oz serving"]
    ["Yuengling Premium Light   ", " 3.3% ABV ", " 12oz serving"]
    ["Yukon Jack ", " 50% ABV ", " 1.5oz serving"]
    ["Zima ", " 4.94% ABV ", " 12oz serving"]
]

console.log(allAlcohols);

let wine1 = Alcohol.create({})